set_property PACKAGE_PIN V17 [get_ports {c}]
    set_property IOSTANDARD LVCMOS33 [get_ports {c}]
set_property PACKAGE_PIN V16 [get_ports {b}]
    set_property IOSTANDARD LVCMOS33 [get_ports {b}]
set_property PACKAGE_PIN W16 [get_ports {e}]
    set_property IOSTANDARD LVCMOS33 [get_ports {e}]
    
set_property PACKAGE_PIN U16 [get_ports {d0}]
    set_property IOSTANDARD LVCMOS33 [get_ports {d0}]
set_property PACKAGE_PIN E19 [get_ports {d1}]
    set_property IOSTANDARD LVCMOS33 [get_ports {d1}]
set_property PACKAGE_PIN U19 [get_ports {d2}]
    set_property IOSTANDARD LVCMOS33 [get_ports {d2}]
set_property PACKAGE_PIN V19 [get_ports {d3}]
    set_property IOSTANDARD LVCMOS33 [get_ports {d3}]
    