#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Feb 25 17:09:42 EST 2026
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 7ebecf90e34e4c8d933e91d1384d1016 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot decoder_2_4_behav xil_defaultlib.decoder_2_4 xil_defaultlib.glbl -log elaborate.log"
xelab -wto 7ebecf90e34e4c8d933e91d1384d1016 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot decoder_2_4_behav xil_defaultlib.decoder_2_4 xil_defaultlib.glbl -log elaborate.log

